export default {
	// FONT
	FONT_SIZE_EXTRA_SMALL: 12,
	FONT_SIZE_SMALL: 14,
	FONT_SIZE_NORMAL: 16,
	FONT_SIZE_MEDIUM: 18,
	FONT_SIZE_LARGE: 20,
	FONT_SIZE_EXTRA_LARGE: 22,

	// FONT FAMILY
	FONG_FAMILY: null,

	// COLORS
	PRIMARY_COLOR: '#27AE60',
	LIGHT_PRIMARY_COLOR: '#27AE6090',
	Text_PRIMARY_COLOR: '#9DA3AB',
	BORDER_RADIUS_COLOR: '#E9E9E9',

	//MOOD_COLORS
	VERY_HAPPY_COLOR: '#27AE60',
	HAPPY_COLOR: '#0D19FC',
	GOOD_COLOR: '#7A6EFC',
	BLEH_COLOR: '#BF991D',
	NOT_SO_GREAT: '#BF1725',
	VERY_UNHAPPY: '#414245',

	//BACKGROUNDCOLORS
	WHITE_BACKGROUND_COLOR: '#FCFBFB',
	LIGHT_BACKGROUND_COLOR: '#F2F2F2',


	// SECONDARY_COLOR: '#63',
	// WHITE_COLOR: '#F2F2F2',
	// SECOND_WHITE_COLOR: '#FCFBFB',
	BLACK_COLOR: '#00000090',
	DARK_COLOR: '#606770',
	LIGHT_COLOR: '#8C8893',
	BACKGROUND_COLOR: '#00000010',

	// WEIGHT
	FONT_WEIGHT_LIGHT: '400',
	FONT_WEIGHT_MEDIUM: '700',
	FONT_WEIGHT_HEAVY: 'bold',

	// BORDER RADIUS
	IMAGE_BORDER_RADIUS: 5,
	BUTTON_BORDER_RADIUS: 5,
	PROFILE_IMAGE_BORDER_RADIUS: 99
};
